config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :projects

  root 'static_pages#home'
  
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'groupsI', to: 'groups#index'
  get '/groups', to: 'groups#new'
  post '/groups', to: 'groups#create'
  get '/logout', to: 'sessions#destroy'
  get '/dashboardU', to: 'users#dashboardU'
  get '/dashboardA', to: 'static_pages#dashboardA'
  get '/add_to_group/:id', to: 'users#add_to_group', :as => 'add_to_group'
  post '/add_to_group', to: 'users#update_group'
  get '/reviews/:id/projreview', to: 'reviews#proj'
  
  resources :groups



  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/dashboardA.html.erb
<% provide(:title, "Admin Dashboard") %>
<% if current_user.admin%>
<div class="centerjumbotron">
  <h1>Admin Dashboard</h1>
  <h2>
  <%= link_to "Groups", groupsI_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Users", users_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Projects", projects_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Reviews", reviews_path, class: "btn btn-lg btn-primary" %>

</div>


  </body>
</html>
<% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>

app/views/static_pages/dashboardU.html.erb
<% provide(:title, "Student Dashboard") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Student Dashboard</title>  </head>
  <body>
    <div class="center jumbotron">
        <h1>Student Dashboard</h1>
        <h1>Welcome, <%= User.email %> </h1>


  <%= link_to "Groups", groupsI_path, class: "btn btn-lg btn-primary" %>

</div>

  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Peer Evaluation Tool</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <% if !current_user %>
  <body>
  
    <div class="centerjumbotron">
        <h1>Duck Debuggers Peer Evaluation Tool</h1>



  <h2><%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary"%>

</div>

  </body>
  <% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>
</html>