config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :projects

  root 'static_pages#home'
  
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'groupsI', to: 'groups#index'
  get '/groups', to: 'groups#new'
  post '/groups', to: 'groups#create'
  get '/logout', to: 'sessions#destroy'
  get '/dashboardU', to: 'users#dashboardU'
  get '/dashboardA', to: 'static_pages#dashboardA'
  get '/add_to_group/:id', to: 'users#add_to_group', :as => 'add_to_group'
  post '/add_to_group', to: 'users#update_group'
  get '/reviews/:id/projreview', to: 'reviews#proj'
  
  resources :groups



  resources :users
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :group, optional: true # A user is not initially assigned to a group
    has_many :reviews, dependent: :delete_all # Allows for deletion of a user to delete all of their reviews
    before_save   :downcase_email
    validates :name, presence: true, length: { maximum: 50 } # Ensures that the user-provided name is under 50 characters
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email.downcase, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true # Valides email so it's under 255 characters using the VALID_EMAIL_REGEX, and it is not already in use
    def downcase_email
        self.email = email.downcase
    end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  # GET /users
  def index
    @Users = User.all
  end

  # GET /users/id
  def show
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    failed = false
    if params[:text]
      users = params[:text].split("\n")
      users = users.reject {|u| u.empty?}
      users.each do |user| 
        print user
        str = user.split(", ")
        @user = User.new
        @user.name = str[0]
        @user.email = str[1]
        if @user.save
        else
          redirect_to signup_path, alert: "Failed at user: #{@user.name}. All previous users were created successfully."
          failed = true
        end
      end
      if !failed
        redirect_to users_path
      end
    else
      @user = User.new(user_params)
      if @user.save
        if current_user
          redirect_to users_path
        else
          redirect_to login_path
        end
      else # not a valid email or password inputted by user
        redirect_to signup_path, alert: "Email in use or invalid email"
      end
    end
  end

  # GET /users/id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PATCH/PUT /reviews/id
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else # User has not been updated yet
      render 'edit'
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # DELETE /users/id
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  # GET /groups
  def add_to_group
    @user = User.find(params[:id])
    @groups = Group.all
  end

  # PATCH/PUT users/groups/id
  def update_group
    @user = User.find(params[:id])
    @group = Group.find(params[:user][:group_id])
    if @user.update(update_group_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else # User not updated to a new group yet
      render 'add_to_group'
    end
  end

  # GET /users
  def dashboardU
    @user = current_user
    @group = @user.group
  end


  private
   # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password_digest, :admin, :group_id)
  end

  def update_group_params
    params.require(:user).permit(:group_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/add_to_group.html.erb
<% if current_user.admin %>
<% provide(:title, "Add to group") %>
<div class="centerjumbotron">
<h1>Add to group</h1>


<%= form_with(model: @user, local: true) do |f| %>
  <div class="flex-container">
  <div class="flex-child">
  <%= f.label :group %>
  </div>
  <div class="flex-child">
  <%= f.select :group_id, @groups.collect { |p| [p.groupname, p.id]}, {}, prompt: 'group'%>
  </div>
  </div>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>


<br>

<h2>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</h2>
</div>
<% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>

app/views/users/dashboardU.html.erb
<% if !current_user.admin%>
<% provide(:title, "Student Dashboard") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Student Dashboard</title>  </head>
  <body>
    <div class="centerjumbotron">
        <h1>Student Dashboard</h1>
        <div class="space"></div>
        <h2 class="left">Welcome, <%= @user.name %> </h2>


<%# add link to user group's projects %>
  <h2 class="left">Group: <%=@user.group.groupname if @user.group%> <%= "No group" if !@user.group%></h2>

  <% if @user.group%>
  <table>
  <thead>
    <tr>
      <th>Project Name</th>
      <th>Description</th>
      <th>Start Date</td>
      <th>End Date</td>
      <th>Group</td>
      <th>Reviews</th>
    </tr>
  </thead>

  <tbody>
    <% @user.group.projects.each do |project| %>
      <tr>
        <td><%= project.projectname %></td>
        <td><%= project.projectdescription %></td>
        <td><%= project.startdate%></td>
        <td><%= project.enddate%></td>
        <td><%= link_to project.group.groupname, project.group if project.group%></td>
        <td><%= link_to "Reviews", controller: "reviews", action: "proj", id: project.id%></td>
      </tr>
    <% end %>
  </tbody>
  <% end%>
</table>
<div class="space"></div>
<h2><%= link_to "Show user", user_path(@user)%></h2>

</div>


  </body>
</html>
<% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% if @user == current_user || current_user.admin%>
<div class="centerjumbotron">
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<h2>
  <%= link_to "Show this user", @user %> |
  <% if current_user.admin%>
  <%= link_to "Back to users", users_path %>
  <% else%>
    <%= link_to "Back to dashboard", dashboardU_path %>
  <% end%>

</h2>
</div>
<% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>

app/views/users/index.html.erb
<% if current_user.admin%>
<div class="centerjumbotron">
<p style="color: green"><%= notice %></p>

<h1>Users</h1>
<div class="space"></div>
<h2><%= link_to "New user", signup_path%></h2>
<div id="users", class="scrollable">
  <% @Users.each do |user| %>
    <%= render user %>
    <div class="left bullet ctext">
      <%= link_to user.name, user %>
    </div>
  <% end %>
</div>
<div class="space"></div>
<h2>
  <%= link_to "Back to dashboard", dashboardA_path if current_user.admin%></h2>
</div>
<% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<%if current_user && current_user.admin%>
  <div class="centerjumbotron">
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
  <h1>Create a User</h1>
  <div>
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
     
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <div class="flex-container">
        <div class="flex-child">
          <%= f.label :admin %>
        </div>
        <div class="flex-child">
          <%= f.check_box :admin%>
        </div>
      </div>
      <%= f.submit "Create User", class: "btn btn-primary" %>
    <% end %>
  </div>
  <br>
  <h1>Create Multiple Users</h1>
  <strong class="ctext">Create a user with the format<br>John Smith, johnsmith@email.com<br>for each line.</strong>
  <div>
    <%= form_with(:url => {:action => 'create'}) do |f| %>
      <%= f.text_area(:text, size: '50x10')%>
      <%= f.submit "Create Users", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
<% elsif !current_user %>
<div class="centerjumbotron">
  <h1>Sign up</h1>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
  <div class="">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
     
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <div class="flex-container">
        <div class="flex-child">
          <%= f.label :admin %>
        </div>
        <div class="flex-child">
          <%= f.check_box :admin%>
        </div>
      </div>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
<% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>

app/views/users/show.html.erb
<% if current_user == @user || current_user.admin %>
<%= render @user %>

<div class="centerjumbotron">
  <h1>User: <%= @user.name%></h1>
  <div class="space"></div>
  <div class="left ctext"><strong>Email: </strong><%= @user.email%></div>
  <% if !@user.admin%>
  <div class="left ctext"><strong>Group: </strong><%= @user.group.groupname if @user.group%></div>
  <% else %>
  <div class="left ctext"><strong>ADMIN</strong>
  <% end%>

  <div class="space"></div>
  <h2><%= link_to "Edit this user", edit_user_path(@user) %> |
  <% if current_user.admin%>
  <% if !@user.admin%>
  <%= link_to "Add to group", add_to_group_path(@user.id)%> |
  <% end%>
  <% end%>
  <%= link_to "Back to users", users_path if current_user.admin%>
  <%= link_to "Back to dashboard", dashboardU_path if !current_user.admin%>
  <div class="space"></div>
  <%= button_to "Destroy this user", @user, method: :delete if current_user.admin && current_user != @user%></h2>

  </h2>
</div>
<% else %>
  <h1>You don't have permission to access this page!</h1>
<%end%>